### ISSUE TITLE
preparations for js-ipfs 0.31

### ISSUE THREAD

**Issue by alanshaw** [ipfs-shipyard/peerpad-core#22]
I upgraded the ipfs dependencies in preparation for js-ipfs 0.31, and ran the e2e tests from peer-pad and they failed :(

https://github.com/ipfs/js-ipfs/issues/1458

```
$ DEBUG=true npm run test:e2e

> peerpad@0.1.0 test:e2e /Users/alan/Code/protocol-labs/peer-pad
> jest --testMatch **/test/e2e/**/*.js

  console.log test/e2e/smoke.test.js:9
    Testing http://localhost:3000

 FAIL  test/e2e/smoke.test.js (254.534s)
  ● creates a pad

    waiting for selector "[data-peer-id]" failed: timeout 120000ms exceeded
      
      at new WaitTask (node_modules/puppeteer/lib/FrameManager.js:840:28)
      at Frame._waitForSelectorOrXPath (node_modules/puppeteer/lib/FrameManager.js:731:12)
      at Frame.waitForSelector (node_modules/puppeteer/lib/FrameManager.js:690:17)
      at Page.waitForSelector (node_modules/puppeteer/lib/Page.js:1008:29)
      at waitForPeerId (test/e2e/smoke.test.js:103:14)
      at Object.<anonymous>.it (test/e2e/smoke.test.js:49:24)

  ● synchronises two pads via IPFS

    waiting for selector "[data-peer-id]" failed: timeout 120000ms exceeded
      
      at new WaitTask (node_modules/puppeteer/lib/FrameManager.js:840:28)
      at Frame._waitForSelectorOrXPath (node_modules/puppeteer/lib/FrameManager.js:731:12)
      at Frame.waitForSelector (node_modules/puppeteer/lib/FrameManager.js:690:17)
      at Page.waitForSelector (node_modules/puppeteer/lib/Page.js:1008:29)
      at waitForPeerId (test/e2e/smoke.test.js:103:14)
      at Object.<anonymous>.it (test/e2e/smoke.test.js:63:27)

  ✕ creates a pad (127338ms)
  ✕ synchronises two pads via IPFS (126488ms)

Test Suites: 1 failed, 1 total
Tests:       2 failed, 2 total
Snapshots:   0 total
Time:        255.364s
Ran all test suites.
```

Additionally this error appeared in the console:

<img width="553" alt="screen shot 2018-07-28 at 21 17 08" src="https://user-images.githubusercontent.com/152863/43360390-721ff20c-92ac-11e8-90ab-19d76edeb7a6.png">

In slightly better news, I manually ran a smoke test with the development server. I started two browser instances and loaded a document. Changes on both sides were reflected on the other with no errors.

**Comment by pgte** [comment]
Hi Alan, thank you for your troubles, but peer-pad-core is no longer being used in peer-pad.
Instead, peer-pad is using peer-star-app, which looks to be working great. Thanks!
